#!/bin/sh

PREREQ=""

prereqs() {
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

remkdir() {
	dir=$1
	rm -rf $dir
	mkdir $dir
}

remkdir ${DESTDIR}/keys

recpexec() {
	file=$1
	dest=$2
	rm -f ${DESTDIR}$dest
	copy_exec $file $dest
}

recpexec /usr/bin/ocaml_cryptsetup /bin/ocaml_cryptsetup
recpexec /bin/stty /bin/stty

exit 0
